
CC = gcc
LIBS = /home/courses/cse533/Stevens/unpv13e/libunp.a -lpthread
FLAGS = -g -O2 
CFLAGS = ${FLAGS} -I/home/courses/cse533/Stevens/unpv13e/lib

all: Multicast-Send Multicast-Receive 
	


Multicast-Send: Multicast-Send.o
	${CC} ${CFLAGS} -o Multicast-Send Multicast-Send.o ${LIBS}
Multicast-Send.o:
	${CC} ${CFLAGS} -c Multicast-Send.c
Multicast-Receive: Multicast-Receive.o
	${CC} ${CFLAGS} -o Multicast-Receive Multicast-Receive.o ${LIBS}
Multicast-Receive.o:
	${CC} ${CFLAGS} -c Multicast-Receive.c
